<?php
$contacts = $this->getContacts();

?>
<div id="contactslist">
    <h2>Liste des contacts</h2>
    <table>
        <tr>
            <th>Name</th>
            <th>email</th>
        </tr>
        <?php if(!empty($contacts)): ?>
            <?php foreach ($contacts as $contact): ?>
                <tr>
                    <td><?php echo $contact->getName(); ?></td>
                    <td><?php echo $contact->getEmail(); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td>there is no contact in this list</td>
        </tr>
    <?php endif; ?>
    </table>
</div>